# Site settings
title: Functional Programming at the University of Kansas
email: andygill@ku.edu
description: "The Functional Programming Group at the University of Kansas applies and extends functional programming technologies to the diverse areas of building computer systems, high-performance computing, information assurance, and telemetry."
baseurl: ""
url: "http://www.ittc.ku.edu/csdl/fpg"
twitter_username: jekyllrb
github_username:  ku-fpg

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!--MORE-->"
exclude: ['_meta','dist','ku-fpg-github-io.cabal','Shake.hs','BibTeX.hs','.cabal-sandbox']

gems:
  - jekyll-redirect-from
